version: '3'

services:
  back-end:
    image: s2t
    container_name: back-end
    restart: unless-stopped
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

  front-end:
    image: s2t-front
    container_name: s2t-front
    restart: unless-stopped
    ports:
      - 3000:3000

  db:
    image: mongo:3.6
    container_name: db
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
